---
- hosts: all
  sudo: yes
  roles:
          - common

- hosts: etcd
  sudo: yes
  tags: etcd
  roles:
          - etcd

- hosts: masters
  sudo: yes
  roles:
          - kubernetes
          - master
          - skydns

- hosts: minions
  sudo: yes
  roles:
          - kubernetes
          - minion
