---
#- include: fedora.yml
#  when: is_rhel7.rc != 0

#- include: rhel7.yml
#  when: is_rhel7.rc == 0

- name: Install docker
  yum: pkg=docker state=latest

- name: write the global config file
  template: src=config.j2 dest=/etc/kubernetes/config
  notify:
          - restart daemons

- name: collect facts about the version of kubernetes
  kube-caps:
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/bin"
