---
- include: fedora.yml
  when: is_rhel7.rc != 0

- include: rhel7.yml
  when: is_rhel7.rc == 0

- name: write the config files for kubelet
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet
  when: not kubelet_use_pre_v10_vars
  notify:
          - restart kubelet

- include: kubelet-old.yaml
  when: kubelet_use_pre_v10_vars

- name: write the config files for proxy
  template: src=proxy.j2 dest=/etc/kubernetes/proxy
  notify:
          - restart proxy

- name: Copy master service files
  copy: src={{ item }} dest=/usr/lib/systemd/system/ mode=644  
  with_fileglob:
        - ./kube*

- name: Daemon reload
  command: "systemctl daemon-reload"

- name: Enable cadvisor
  service: name=cadvisor enabled=yes state=started
  when: has_cadvisor.rc == 0

- name: Enable kubelet
  service: name=kubelet enabled=yes state=started

- name: Enable proxy
  service: name=kube-proxy enabled=yes state=started

#- include: firewalld.yml
#  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0
